//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitaciones
    {
        public int IdInvitacion { get; set; }
        public string CorreoRemitente { get; set; }
        public string CorreoDestinatario { get; set; }
        public int Jugador_IdJugador { get; set; }
    
        public virtual Jugadores Jugadores { get; set; }
    }
}
